[package]
name = "mat_fac_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
ndarray = "0.15.4"
ndarray-rand = "0.14"
rand = "0.8"